/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cenfotec.componentes.control;

/**
 *
 * @author alego
 */
public class CifradorCesar extends javax.swing.JPanel {

    /**
     * Creates new form CifradorCesar
     */
    public CifradorCesar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brnDesencriptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblResul = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPalabra = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        btnEncriptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 255, 102));

        brnDesencriptar.setText("Desencriptar");
        brnDesencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnDesencriptarActionPerformed(evt);
            }
        });

        jLabel1.setText("WORD");

        jLabel2.setText("KEY");

        lblResul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblResul.setText("jLabel3");

        jLabel3.setText("Cifrado de Cesar");

        btnEncriptar.setText("Encriptar");
        btnEncriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncriptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblResul)
                                    .addComponent(btnEncriptar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brnDesencriptar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncriptar)
                    .addComponent(brnDesencriptar))
                .addGap(18, 18, 18)
                .addComponent(lblResul)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncriptarActionPerformed

        int key = Integer.parseInt(this.txtClave.getText());
        String word = this.txtPalabra.getText().toLowerCase();

        StringBuilder cifrado = new StringBuilder(word.length());

        int ASCII = 0;

        for(int i = 0; i < word.length(); i++){

            ASCII = (int)word.charAt(i);
            
            ASCII = ASCII + key;
            
            if(ASCII > 122){
                ASCII = 96 + (ASCII - 122);
            }

            cifrado.append((char) ASCII);

        }

        this.lblResul.setText(cifrado.toString());

    }//GEN-LAST:event_btnEncriptarActionPerformed

    private void brnDesencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnDesencriptarActionPerformed
        
        int key = Integer.parseInt(this.txtClave.getText());
        String word = this.txtPalabra.getText().toLowerCase();

        StringBuilder cifrado = new StringBuilder(word.length());

        int ASCII = 0;

        for(int i = 0; i < word.length(); i++){

            ASCII = (int)word.charAt(i);
            
            ASCII = ASCII - key;
            
            if(ASCII < 97){
                System.out.println(" se paso: " + (ASCII - 96));
                ASCII = 122 + (ASCII - 96);
            }

            cifrado.append((char) ASCII);

        }

        this.lblResul.setText(cifrado.toString());
        
    }//GEN-LAST:event_brnDesencriptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnDesencriptar;
    private javax.swing.JButton btnEncriptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblResul;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtPalabra;
    // End of variables declaration//GEN-END:variables
}
